function chllabNBlookup = import_labNBlookup(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  CHLLABNBLOOKUP = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  CHLLABNBLOOKUP = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  CHLLABNBLOOKUP = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  chllabNBlookup = importfile("\\sosiknas1\lab_data\LTER\CHL\chl_labNBlookup.xlsx", "Sheet1", [2, 253]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-May-2022 13:17:09

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 500];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["labNB", "date", "VarName3"];
opts.VariableTypes = ["categorical", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, "VarName3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["labNB", "VarName3"], "EmptyFieldRule", "auto");

% Import the data
chllabNBlookup = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    chllabNBlookup = [chllabNBlookup; tb]; %#ok<AGROW>
end

%import function just hard set to import 500 rows from xlsx file to accomodate future entries, 
% empty rows are nans to get rid of those
chllabNBlookup = chllabNBlookup(~isnan(chllabNBlookup.date),:); 

end