%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\heidi\Downloads\NESLTER_EN657_2_annotations.csv
%
% Auto-generated by MATLAB on 26-Jul-2021 17:47:52

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["roi_id", "Var2", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = "roi_id";
opts.VariableTypes = ["string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["roi_id", "Var2", "Var3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["roi_id", "Var2", "Var3", "Var4", "Var5"], "EmptyFieldRule", "auto");

% Import the data
NESLTEREN6572annotations = readtable("C:\Users\heidi\Downloads\NESLTER_EN657_2_annotations.csv", opts);


%% Clear temporary variables
clear opts