function mytable = importfile1(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   NESLTEREN60801FEB2018C = IMPORTFILE1(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   NESLTEREN60801FEB2018C = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   NESLTEREN60801Feb2018C = importfile1('NESLTER_EN608_01Feb2018C.csv', 1, 376);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/02/10 18:47:42

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[3,4,5,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [3,4,5,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]);
rawCellColumns = raw(:, [1,2,6,7,8,9,10,11]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
mytable = table;
mytable.Plate = rawCellColumns(:, 1);
mytable.Experiment = rawCellColumns(:, 2);
mytable.Group = cell2mat(rawNumericColumns(:, 1));
mytable.Filename = cell2mat(rawNumericColumns(:, 2));
mytable.Sample = cell2mat(rawNumericColumns(:, 3));
mytable.Workspace = rawCellColumns(:, 3);
mytable.CompensationSource = rawCellColumns(:, 4);
mytable.PlotTitle = rawCellColumns(:, 5);
mytable.Gate = rawCellColumns(:, 6);
mytable.XParameter = rawCellColumns(:, 7);
mytable.YParameter = rawCellColumns(:, 8);
mytable.Count = cell2mat(rawNumericColumns(:, 4));
mytable.Volume = cell2mat(rawNumericColumns(:, 5));
mytable.Concentration = cell2mat(rawNumericColumns(:, 6));
mytable.Total = cell2mat(rawNumericColumns(:, 7));
mytable.Gated = cell2mat(rawNumericColumns(:, 8));
mytable.XMean = cell2mat(rawNumericColumns(:, 9));
mytable.YMean = cell2mat(rawNumericColumns(:, 10));
mytable.XMedian = cell2mat(rawNumericColumns(:, 11));
mytable.YMedian = cell2mat(rawNumericColumns(:, 12));
mytable.XPeak = cell2mat(rawNumericColumns(:, 13));
mytable.YPeak = cell2mat(rawNumericColumns(:, 14));
mytable.XSD = cell2mat(rawNumericColumns(:, 15));
mytable.YSD = cell2mat(rawNumericColumns(:, 16));
mytable.XCV = cell2mat(rawNumericColumns(:, 17));
mytable.YCV = cell2mat(rawNumericColumns(:, 18));
mytable.XrSD = cell2mat(rawNumericColumns(:, 19));
mytable.YrSD = cell2mat(rawNumericColumns(:, 20));
mytable.XrCV = cell2mat(rawNumericColumns(:, 21));
mytable.YrCV = cell2mat(rawNumericColumns(:, 22));

